import './globals.css'
import ReduxProvider from './store/provider'

export const metadata = {
  title: 'Instagram',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
